version: "3"

services:
  db:
    image: mysql
    environment:
       MYSQL_DATABASE: charles_db
       MYSQL_ROOT_PASSWORD: xhongcc
    volumes:
      - ./db:/var/lib/mysql
    restart: always

  redis:
    image: redis
    restart: always

  memcached:
    image: memcached
    restart: always

  web:
    build: ../charles
    ports:
    - "8088:8088"
    volumes:
    - ../charles:/charles
    - /tmp/logs:/tmp
    command: bash start.sh
    links:
    - redis
    - memcached
    - db
    depends_on:
      - db
    restart: always


  nginx:
    build: ./nginx
    ports:
    - "80:80"
    volumes:
    - ../charles/static:/usr/share/nginx/html/static:ro
    - ../charles/media:/usr/share/nginx/html/media:ro
    links:
    - web
    depends_on:
    - web
    restart: always
