# Generated by Django 2.2.14 on 2020-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=99, help_text='置顶'),
        ),
    ]
