# Generated by Django 2.2.9 on 2020-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=64)),
                ('room_description', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=255)),
                ('channel_no', models.CharField(max_length=8)),
            ],
        ),
    ]
