# Generated by Django 2.2.9 on 2020-01-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200111_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unicode_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
