# Generated by Django 2.2.9 on 2020-01-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20200111_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('said_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='said_to', to=settings.AUTH_USER_MODEL)),
                ('said_to_room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
                ('who_said', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='who_said', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
