# Generated by Django 2.2.9 on 2020-03-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='msg_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
