# Generated by Django 2.2.9 on 2020-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatlog_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
