# Generated by Django 2.2.3 on 2020-03-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userprofile_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='said_to_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='said_to_room', to='chat.ChatRoom'),
        ),
    ]
