# Generated by Django 2.2.9 on 2020-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userprofile_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(related_name='chat_admins', to='chat.UserProfile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='img_path',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_description',
            field=models.CharField(default='这里还没什么描述', max_length=255),
        ),
    ]
