# Generated by Django 2.2.9 on 2020-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200326_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_member', to='chat.UserProfile'),
        ),
    ]
