# Generated by Django 2.2.9 on 2020-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200326_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='channel_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
