# Generated by Django 2.2.3 on 2020-03-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200323_1226'),
        ('chat', '0010_auto_20200326_1514'),
    ]

    operations = [
    ]
