# Generated by Django 2.2.3 on 2020-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_merge_20200327_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_path',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
