# Generated by Django 2.2.9 on 2020-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200327_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ordering',
            field=models.IntegerField(default=99),
        ),
    ]
