# Generated by Django 2.2.3 on 2020-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200327_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ordering',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_member', to='chat.UserProfile'),
        ),
    ]
