# Generated by Django 2.2.11 on 2020-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatroom_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_member', to='chat.UserProfile'),
        ),
    ]
