# Generated by Django 2.2.3 on 2020-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200402_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='status',
            field=models.CharField(default='read', max_length=16),
        ),
    ]
