# Generated by Django 2.2.11 on 2020-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='said_together',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
