# Generated by Django 2.2.11 on 2020-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_heroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='common_ordering',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='popular_ordering',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='relative_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
